### ISSUE TITLE
Initial alpha release

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [SnailyCAD/snaily-cadv4#1]
# Todo

- [x] setup client app
	- [x] tailwindcss
	- [x] next.js
	- [x] typescript
- [x] user auth flow
	- [x] register
	- [x] login
	- [x] user settings 
- [x] 🏃‍♂️ cad settings
- [x] 🏃‍♂️ manage users
- [x] 🏃‍♂️ admin values
- [x] citizen flow
	- [x] create citizen
	- [x] view citizens
	- [x] #4
	- [ ] ~~🏃‍♂️ view individual citizen~~
	- [x] edit citizen
	- [x] manage licenses
	- [x] edit vehicles & weapons 
	- [x] manage vehicles
	- [x] manage weapons
- [x] add GitHub workflows
