### ISSUE TITLE
feat: Dispatch Private Messaging

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [SnailyCAD/snaily-cadv4#1644]
### Describe the feature

Allow Dispatch to PM active units:

```[tasklist]
### Tasks
- [x] Dispatch can send information to unit (search, call, incident)
- [x] notification toast for a new message when chat is not opened
- [x] messages get deleted once unit goes off-duty
- [x] **1 directional:** Dispatch can only create a PM chat -> unit can reply once the chat is created
```

### Additional Context

https://discord.com/channels/792479048457912360/1108657815461040159
