### ISSUE TITLE
Optional Feature: Visible Incidents

### ISSUE THREAD

**Issue by jxckUK** [SnailyCAD/snaily-cadv4#1705]
### Describe the feature

At the moment by design, only dispatchers may see and modify active incidents.

It would be good if there was an additional optional feature that allows EMS/FD & LEO to see these incidents in their dashboards and attach, the same behaviour as we currently have for active calls.

An additional request is that there be an optional feature to allow EMS/FD & LEO to create incidents in their dashboards. This is useful to some regions like the UK where dispatchers are unavailable or not active and the officer or service member needs to record a traffic stop or some other spontaneous activity.

```[tasklist]
### Tasks
- [x] Readonly incidents for LEO/EMS/FD dashboards
- [x] Allow LEO/EMS/FD to attach themselves to an active incident
- [ ] Editable incidents for LEO/EMS/FD dashboards with added permissions (`ManageActiveIncidents` each for EMS/FD and LEO)
```

**Comment by bartusek27** [comment]
+1 here, makes sense. We are handling the incidents as some kind of case report. It would also be nice to have ability to have more permission granularity per each incident so officers can define what role or specific persons are available to View or Edit the incident.
