### ISSUE TITLE
Public API access

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [SnailyCAD/snaily-cadv4#99]
## Todo

- [x] generated API key can be used to access CAD
- [ ] able to generate an API key
	- [x] db model 
	- [x] initial setup
	- [ ] allow selecting routes (owner-only and some admin routes will **not** be allowed)

**Comment by pp2amd6** [comment]
What kind of authorization is supposed to be?
I suggest a webhook

**Comment by Dev-CasperTheGhost** [comment]
> 
> 
> What kind of authorization is supposed to be? I suggest a webhook

This is so owners/developers can make scripts that can access certain routes in the CAD.

**Comment by pp2amd6** [comment]
Those. there will be no API in CAD? Will you need to develop the API yourself?

**Comment by Dev-CasperTheGhost** [comment]
The API is already there. It's the folder at: `./packages/api`

**Comment by pp2amd6** [comment]
I can't figure out how the API method identification and execution permission will go. What will the request look like?

**Comment by Dev-CasperTheGhost** [comment]
Currently you have to be logged in to access the API (with the `snaily-cad-session` cookie.), the ability to add an API Token as owner will allow that token to be used as authentication to the API.

**Comment by pp2amd6** [comment]
Will the token be passed in the header or in the link?
What steps will I have to take to use the API?

**Comment by Dev-CasperTheGhost** [comment]
The token should be passed via the headers. The steps to use the API will be explained once the implementation is finished in the docs.

**Comment by Dev-CasperTheGhost** [comment]
@pp2amd6 docs are now live here: https://cad-docs.netlify.app/other/public-api
